env:
  browser: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'airbnb'
  - 'airbnb/hooks'
settings:
  react:
    version: detect
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
parser: babel-eslint
plugins:
  - react
rules:
  import/extensions: 'off'
  react/state-in-constructor: 'off'
  react/jsx-filename-extension:
    - 1
    - extensions:
      - ".js"
      - ".jsx"
  import/prefer-default-export: 'off'
  no-shadow: 'off'
  import/order: 'off'

